# Generated by Django 4.1.3 on 2022-11-14 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 14, 12, 42, 7, 603750, tzinfo=datetime.timezone.utc)),
        ),
    ]
