# Generated by Django 4.1.3 on 2022-11-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0003_alter_post_date_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='topics',
            field=models.CharField(choices=[('philosophy', 'Philosophy'), ('MyLife', 'mylife')], default='philosophy', max_length=30),
        ),
    ]
